"""added guardians

Revision ID: e5fdf372a418
Revises: 56c2b710f30a
Create Date: 2025-03-05 10:39:32.065429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5fdf372a418'
down_revision = '56c2b710f30a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('guardian_name', sa.String(), nullable=True))
    op.add_column('student', sa.Column('guardian_contact', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'guardian_contact')
    op.drop_column('student', 'guardian_name')
    # ### end Alembic commands ###
